services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  service-db:
    build: ./TicketSalesAPI
    container_name: service-db
    ports:
      - "8080:8080"
    environment:
      - EventStoreDatabase__ConnectionString=mongodb://mongodb:27017
      - EventStoreDatabase__DatabaseName=TicketSalesDB
      - EventStoreDatabase__EventsCollectionName=Events
      - ASPNETCORE_ENVIRONMENT=Development
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped

  service-nodb:
    build: ./TicketSalesAPI_NoDB
    container_name: service-nodb
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - service-db
      - service-nodb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "object-created-topic:1:1,confirmation-topic:1:1"
    ports:
      - "9092:9092"
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - "9000:9000"
    restart: unless-stopped

volumes:
  mongo_data: