### 1. Получение JWT-токена
POST http://localhost:7000/auth/login
Content-Type: application/json

{
  "username": "Роза Барбоскина",
  "password": "Barbos16"
}

### 2. Получение всех мероприятий через API Gateway
GET http://localhost:7000/ticketsales/events

### 3. Создание мероприятия через API Gateway с корректным токеном
POST http://localhost:7000/ticketsales/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTBmNGMyNmJhNzVmOWI4OTcxYWQ2ZTIiLCJ1bmlxdWVfbmFtZSI6ItCg0L7Qt9CwINCR0LDRgNCx0L7RgdC60LjQvdCwIiwianRpIjoiNTc5MWRjOGY2YzE2NDAyZmExMjU3YjdjNmY1NjE0Y2UiLCJuYmYiOjE3NzkzODc4NTcsImV4cCI6MTc3OTM4ODc1NywiaXNzIjoiVGlja2V0U2FsZXMuQXV0aCIsImF1ZCI6IlRpY2tldFNhbGVzLkFwaSJ9.exGC9XWpLkvGUYaVlHBGy6XHQknQk_4clyH5oe5MteE

{
  "name": "Концерт",
  "date": "2026-12-31T19:00:00Z",
  "hallType": 2,
  "availableTickets": 10,
  "price": 2500,
  "userId": "test123"
}

### 4. Создание мероприятия без токена
POST http://localhost:7000/ticketsales/events
Content-Type: application/json

{
  "name": "Неавторизованная попытка",
  "date": "2026-12-31T19:00:00Z",
  "hallType": 0,
  "availableTickets": 14,
  "price": 2500,
  "userId": "test123"
}